IMG = blochsphere.pdf weylchamber.pdf fouriercircuit.pdf dynmap.pdf

include ../figures.mk

blochsphere.pdf: blochsphere.py

weylchamber.pdf: weylchamber.py

fouriercircuit.pdf: fouriercircuit.tex

dynmap.pdf: dynmap.tex

clean: clean-auto
