IMG = ryd3_levels.pdf ryd3_favg.pdf ryd3_nodiss_pulses.pdf \
      ryd3_nodiss_popdyn.pdf ryd3_diss_pulses.pdf ryd3_diss_popdyn.pdf \
      tm3_fulldiss_favg.pdf tm3_weakdiss_favg.pdf tm3_fulldiss_pulses.pdf \
      tm3_fulldiss_popdyn01.pdf tm3_fulldiss_popdyn11.pdf
IMG2 =

include ../figures.mk

ryd3_levels.pdf: ryd3_levels.tex

ryd3_favg.pdf: ryd3_favg.agr

ryd3_nodiss_pulses.pdf: ryd3_nodiss_pulses.agr

ryd3_nodiss_popdyn.pdf: ryd3_nodiss_popdyn.agr

ryd3_diss_pulses.pdf: ryd3_diss_pulses.agr

ryd3_diss_popdyn.pdf: ryd3_diss_popdyn.agr

tm3_fulldiss_favg.pdf: tm3_fulldiss_favg.agr

tm3_weakdiss_favg.pdf: tm3_weakdiss_favg.agr

tm3_fulldiss_pulses.pdf: tm3_fulldiss_pulses.agr

tm3_fulldiss_popdyn01.pdf: tm3_fulldiss_popdyn01.agr

tm3_fulldiss_popdyn11.pdf: tm3_fulldiss_popdyn11.agr

clean: clean-auto
