IMG = weyl_paths.pdf tm_conv_LI.pdf tm_conv_favg.pdf controllability.pdf fpe_topology.pdf

include ../figures.mk

weyl_paths.pdf: weyl_paths.py
tm_conv_LI.pdf: tm_conv_LI.agr
tm_conv_favg.pdf: tm_conv_favg.agr
controllability.pdf: controllability.py
fpe_topology.pdf: fpe_topology.py

clean: clean-auto
