IMG = weyl_paths.pdf tm_conv_LI.pdf tm_conv_favg.pdf
IMG2 = Josephson-Junction.pdf JCQ-1pulse.pdf JCQ-1pulse-polyhedron.pdf JCQ-2pulses.pdf JCQ-2pulses-polyhedron.pdf

include ../figures.mk

weyl_paths.pdf: weyl_paths.py
tm_conv_LI.pdf: tm_conv_LI.agr
tm_conv_favg.pdf: tm_conv_favg.agr

clean: clean-auto
