IMG = RydRobust_1q_levels.pdf blackman_seq_pulses.pdf stirap_pulses.pdf \
      mixed_pulses.pdf rydberg_qsl.pdf jaksch_zoller_pop_phase.pdf \
      stirap_blockade.pdf robustness.pdf robust_oct_pulses.pdf \
	  robust_oct_pop.pdf robust_oct_pulses100.pdf robust_oct_pop100.pdf \
	  robustness_oct.pdf
IMG2 =

include ../figures.mk

RydRobust_1q_levels.pdf: RydRobust_1q_levels.tex

blackman_seq_pulses.pdf: blackman_seq_pulses.py

stirap_pulses.pdf: stirap_pulses.py

mixed_pulses.pdf: mixed_pulses.py

rydberg_qsl.pdf: rydberg_qsl.py

jaksch_zoller_pop_phase.pdf: jaksch_zoller_pop_phase.py

stirap_blockade.pdf: stirap_blockade.py

robustness.pdf: robustness.py

robust_oct_pulses.pdf: robust_oct_pulses.py

robust_oct_pop.pdf: robust_oct_pop.py

robust_oct_pulses100.pdf: robust_oct_pulses100.py

robust_oct_pop100.pdf: robust_oct_pop100.py

robustness_oct.pdf: robustness_oct.py

clean: clean-auto
