# Rules to be used by the image makefiles in chapter subfolders
#
# The IMG variable must be defined before including this file, and contain the
# names of images that are generated by MAKE
#
# The IMG2 variable may further list files that are are not generated from
# other files but should be copied directly

.DEFAULT_GOAL = all
all: $(IMG)
	@cp -p $(IMG) $(IMG2) ../../figures/

diss.cls: ../../diss.cls
	@cp ../../diss.cls diss.cls

mymacros.sty: ../../mymacros.sty
	@cp ../../mymacros.sty mymacros.sty

packages: ../../packages/Kassel/style.sty
	@cp -r ../../packages packages

%.pdf: %.tex diss.cls mymacros.sty packages
	@latexmk -pdf -pdflatex="pdflatex -file-line-error -interaction=nonstopmode -halt-on-error" -use-make -silent $<

%.pdf: %.agr
	@../../scripts/xmgrace_parser.py --hardcopy $@ $<

clean-auto:
	@rm -f *.end
	@rm -f *.aux
	@rm -f *.log
	@rm -f *.toc
	@rm -f *.bbl
	@rm -f *.blg
	@rm -f *.out
	@rm -f *.bak
	@rm -f *.lof
	@rm -f *.fdb_latexmk
	@rm -f *.fls
	@rm -f *~
	@rm -f *.dvi
	@rm -f *.ps
	@rm -f *.preview.pdf
	@rm -rf $(IMG)
	@rm -rf diss.cls mymacros.sty packages
