IMG = jj.pdf rip_entanglement.pdf transmonKITP_gate_error.pdf
IMG2 =

include ../figures.mk

jj.pdf: jj.tex

rip_entanglement.pdf: rip_entanglement.py

transmonKITP_gate_error.pdf: transmonKITP_gate_error.py

clean: clean-auto
